version: '3.4'

services:
    api-gateway:
        depends_on: [service1, service2]
        image: api-gateway:latest
        container_name: api-gateway
        restart: always
        ports: 
            - 80:80
            - 443:443
        build: 
            context: ./ApiGateway/.
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Password=SUPERSECUREPASSWORD
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
          - ~/.aspnet/https:/https:ro

    service1:
        image: service1:latest
        container_name: service1
        restart: always
        build: 
            context: ./Service1/.
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Password=SUPERSECUREPASSWORD
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
          - ~/.aspnet/https:/https:ro

    service2:
        image: service2:latest
        container_name: service2
        restart: always
        build: 
            context: ./Service2/.
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:443;http://+:80
          - ASPNETCORE_Kestrel__Certificates__Default__Password=SUPERSECUREPASSWORD
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
          - ~/.aspnet/https:/https:ro
