version: '3.4'

services:
    api-gateway:
        depends_on: [service1, service2]
        image: api-gateway:latest
        container_name: api-gateway
        restart: always
        ports: 
            - 5001:5000
        build: 
            context: ./ApiGateway/.

    service1:
        image: service1:latest
        container_name: service1
        restart: always
        build: 
            context: ./Service1/.

    service2:
        image: service2:latest
        container_name: service2
        restart: always
        build: 
            context: ./Service2/.
